/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VideoDownloadService } from "../videoDownload.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoDownloadCreateInput } from "./VideoDownloadCreateInput";
import { VideoDownload } from "./VideoDownload";
import { VideoDownloadFindManyArgs } from "./VideoDownloadFindManyArgs";
import { VideoDownloadWhereUniqueInput } from "./VideoDownloadWhereUniqueInput";
import { VideoDownloadUpdateInput } from "./VideoDownloadUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VideoDownloadControllerBase {
  constructor(
    protected readonly service: VideoDownloadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VideoDownload })
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVideoDownload(
    @common.Body() data: VideoDownloadCreateInput
  ): Promise<VideoDownload> {
    return await this.service.createVideoDownload({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        downloadStatus: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [VideoDownload] })
  @ApiNestedQuery(VideoDownloadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoDownloads(
    @common.Req() request: Request
  ): Promise<VideoDownload[]> {
    const args = plainToClass(VideoDownloadFindManyArgs, request.query);
    return this.service.videoDownloads({
      ...args,
      select: {
        createdAt: true,
        downloadStatus: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VideoDownload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async videoDownload(
    @common.Param() params: VideoDownloadWhereUniqueInput
  ): Promise<VideoDownload | null> {
    const result = await this.service.videoDownload({
      where: params,
      select: {
        createdAt: true,
        downloadStatus: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        videoUrl: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VideoDownload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVideoDownload(
    @common.Param() params: VideoDownloadWhereUniqueInput,
    @common.Body() data: VideoDownloadUpdateInput
  ): Promise<VideoDownload | null> {
    try {
      return await this.service.updateVideoDownload({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          downloadStatus: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VideoDownload })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVideoDownload(
    @common.Param() params: VideoDownloadWhereUniqueInput
  ): Promise<VideoDownload | null> {
    try {
      return await this.service.deleteVideoDownload({
        where: params,
        select: {
          createdAt: true,
          downloadStatus: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          videoUrl: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
