/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VideoDownload } from "./VideoDownload";
import { VideoDownloadCountArgs } from "./VideoDownloadCountArgs";
import { VideoDownloadFindManyArgs } from "./VideoDownloadFindManyArgs";
import { VideoDownloadFindUniqueArgs } from "./VideoDownloadFindUniqueArgs";
import { DeleteVideoDownloadArgs } from "./DeleteVideoDownloadArgs";
import { VideoDownloadService } from "../videoDownload.service";
@graphql.Resolver(() => VideoDownload)
export class VideoDownloadResolverBase {
  constructor(protected readonly service: VideoDownloadService) {}

  async _videoDownloadsMeta(
    @graphql.Args() args: VideoDownloadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VideoDownload])
  async videoDownloads(
    @graphql.Args() args: VideoDownloadFindManyArgs
  ): Promise<VideoDownload[]> {
    return this.service.videoDownloads(args);
  }

  @graphql.Query(() => VideoDownload, { nullable: true })
  async videoDownload(
    @graphql.Args() args: VideoDownloadFindUniqueArgs
  ): Promise<VideoDownload | null> {
    const result = await this.service.videoDownload(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VideoDownload)
  async deleteVideoDownload(
    @graphql.Args() args: DeleteVideoDownloadArgs
  ): Promise<VideoDownload | null> {
    try {
      return await this.service.deleteVideoDownload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
