/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VideoDownload } from "./VideoDownload";
import { VideoDownloadCountArgs } from "./VideoDownloadCountArgs";
import { VideoDownloadFindManyArgs } from "./VideoDownloadFindManyArgs";
import { VideoDownloadFindUniqueArgs } from "./VideoDownloadFindUniqueArgs";
import { DeleteVideoDownloadArgs } from "./DeleteVideoDownloadArgs";
import { VideoDownloadService } from "../videoDownload.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => VideoDownload)
export class VideoDownloadResolverBase {
  constructor(
    protected readonly service: VideoDownloadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "read",
    possession: "any",
  })
  async _videoDownloadsMeta(
    @graphql.Args() args: VideoDownloadCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VideoDownload])
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "read",
    possession: "any",
  })
  async videoDownloads(
    @graphql.Args() args: VideoDownloadFindManyArgs
  ): Promise<VideoDownload[]> {
    return this.service.videoDownloads(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VideoDownload, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "read",
    possession: "own",
  })
  async videoDownload(
    @graphql.Args() args: VideoDownloadFindUniqueArgs
  ): Promise<VideoDownload | null> {
    const result = await this.service.videoDownload(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VideoDownload)
  @nestAccessControl.UseRoles({
    resource: "VideoDownload",
    action: "delete",
    possession: "any",
  })
  async deleteVideoDownload(
    @graphql.Args() args: DeleteVideoDownloadArgs
  ): Promise<VideoDownload | null> {
    try {
      return await this.service.deleteVideoDownload(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
